version: '3'

services:
  geth:
    image: "ethereum/client-go"
    hostname: "geth"
    command: "--fast --datadir /opt/chain"
    volumes:
      - "/opt/chain:/opt/chain"
    restart: always
  server:
    image: "marceloneil/ikb-server:latest"
    ports:
      - "80:3000"
    volumes:
      - "/opt/chain:/opt/chain"
    restart: always
    depends_on:
      - geth