version: '2'

services:
  geth:
    image: "ethereum/client-go"
    command: "--fast --datadir /opt/chain --ws --wsaddr 0.0.0.0 --wsorigins *"
    volumes:
      - "chain:/opt/chain"
    restart: always
  server:
    image: "marceloneil/ikb-server:latest"
    ports:
      - "80:3000"
    restart: always
    depends_on:
      - geth

volumes:
  chain: